import * as yup from 'yup';
import { DayReviewThreadValue } from './dayReview';
import { DefaultThreadValue } from './default';
import { ImpulseThreadValue } from './impulse';
import { SuggestionThreadValue } from './suggestion';
import { WhatsappThreadValue } from './whatsapp';
export * from './dayReview';
export * from './default';
export * from './impulse';
export * from './suggestion';
export * from './whatsapp';
export type ThreadValue = DefaultThreadValue | WhatsappThreadValue | ImpulseThreadValue | DayReviewThreadValue | SuggestionThreadValue;
export declare const threadSchemas: Record<ThreadValue['type'], yup.ObjectSchema<ThreadValue>>;
export declare const threadSchema: yup.Lazy<ThreadValue, yup.AnyObject, any>;
