"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isAffirmationTactic = exports.isTaskTactic = exports.isBreatheTactic = exports.isVideoTactic = exports.isStepsTactic = void 0;
const isStepsTactic = ({ type }) => type === 'steps';
exports.isStepsTactic = isStepsTactic;
const isVideoTactic = ({ type }) => type === 'video';
exports.isVideoTactic = isVideoTactic;
const isBreatheTactic = ({ type }) => type === 'breathingExercise';
exports.isBreatheTactic = isBreatheTactic;
const isTaskTactic = ({ type }) => type === 'task';
exports.isTaskTactic = isTaskTactic;
const isAffirmationTactic = ({ type }) => type === 'affirmation';
exports.isAffirmationTactic = isAffirmationTactic;
