import * as yup from 'yup';
export declare const patternSchema: yup.ObjectSchema<{
    uid: string;
    updatedAt: import("..").TimestampLike | yup.Maybe<null>;
    createdAt: import("..").TimestampLike | yup.Maybe<null>;
    name: string;
    ordinal: number;
    supportGroupIds: string[] | undefined;
    notification: yup.Maybe<{} | undefined> | {
        title: string;
        body: string;
    };
    measureTactic: {
        createdAt?: import("..").TimestampLike | yup.Maybe<null>;
        updatedAt?: import("..").TimestampLike | yup.Maybe<null>;
        uid?: string | null | undefined;
        sourceId?: string | undefined;
        subtitle?: yup.Maybe<string | undefined>;
        description?: string | null | undefined;
        image?: {
            localFilePath?: yup.Maybe<string | undefined>;
            storagePath?: yup.Maybe<string | undefined>;
            uri?: yup.Maybe<string | undefined>;
        } | null | undefined;
        isTemplate?: boolean | null | undefined;
        language?: string | null | undefined;
        href?: string | null | undefined;
        categoryIds?: (string | undefined)[] | null | undefined;
        isShared?: boolean | null | undefined;
        isResponseRequired?: boolean | null | undefined;
        timerSeconds?: yup.Maybe<number | undefined>;
        isAvailableForRecommendation?: boolean | null | undefined;
        numberOfLikes?: number | null | undefined;
        isSuggested?: boolean | undefined;
        lowEmoji?: yup.Maybe<string | undefined>;
        highEmoji?: yup.Maybe<string | undefined>;
        type: "measure-slider";
        title: string;
        backgroundColor: string;
    } | {
        createdAt?: import("..").TimestampLike | yup.Maybe<null>;
        updatedAt?: import("..").TimestampLike | yup.Maybe<null>;
        uid?: string | null | undefined;
        sourceId?: string | undefined;
        subtitle?: yup.Maybe<string | undefined>;
        description?: string | null | undefined;
        image?: {
            localFilePath?: yup.Maybe<string | undefined>;
            storagePath?: yup.Maybe<string | undefined>;
            uri?: yup.Maybe<string | undefined>;
        } | null | undefined;
        isTemplate?: boolean | null | undefined;
        language?: string | null | undefined;
        href?: string | null | undefined;
        categoryIds?: (string | undefined)[] | null | undefined;
        isShared?: boolean | null | undefined;
        isResponseRequired?: boolean | null | undefined;
        timerSeconds?: yup.Maybe<number | undefined>;
        isAvailableForRecommendation?: boolean | null | undefined;
        numberOfLikes?: number | null | undefined;
        isSuggested?: boolean | undefined;
        type: "measure-time";
        title: string;
        backgroundColor: string;
    } | {
        createdAt?: import("..").TimestampLike | yup.Maybe<null>;
        updatedAt?: import("..").TimestampLike | yup.Maybe<null>;
        uid?: string | null | undefined;
        sourceId?: string | undefined;
        subtitle?: yup.Maybe<string | undefined>;
        description?: string | null | undefined;
        image?: {
            localFilePath?: yup.Maybe<string | undefined>;
            storagePath?: yup.Maybe<string | undefined>;
            uri?: yup.Maybe<string | undefined>;
        } | null | undefined;
        isTemplate?: boolean | null | undefined;
        language?: string | null | undefined;
        href?: string | null | undefined;
        categoryIds?: (string | undefined)[] | null | undefined;
        isShared?: boolean | null | undefined;
        isResponseRequired?: boolean | null | undefined;
        timerSeconds?: yup.Maybe<number | undefined>;
        isAvailableForRecommendation?: boolean | null | undefined;
        numberOfLikes?: number | null | undefined;
        isSuggested?: boolean | undefined;
        type: "measure-counter";
        title: string;
        backgroundColor: string;
    };
    dailySetbackThreshold: yup.Maybe<number | undefined>;
    setbackThreshold: yup.Maybe<number | undefined>;
    issueId: yup.Maybe<string | undefined>;
    parentIssueIds: string[] | undefined;
    sendWeeklyReports: yup.Maybe<boolean | undefined>;
}, yup.AnyObject, {
    uid: undefined;
    updatedAt: undefined;
    createdAt: undefined;
    name: undefined;
    ordinal: undefined;
    supportGroupIds: "";
    notification: undefined;
    measureTactic: undefined;
    dailySetbackThreshold: undefined;
    setbackThreshold: undefined;
    issueId: undefined;
    parentIssueIds: "";
    sendWeeklyReports: undefined;
}, "">;
export type PatternValue = yup.InferType<typeof patternSchema>;
