"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isRecapTactic = exports.isContactsTactic = exports.isTaskTactic = exports.isBreatheTactic = exports.isVideoTactic = exports.isAudioTactic = exports.isStepsTactic = void 0;
const lodash_1 = require("lodash");
const recap_1 = require("../recap");
const isStepsTactic = ({ type }) => type === 'steps';
exports.isStepsTactic = isStepsTactic;
const isAudioTactic = ({ type }) => type === 'audio';
exports.isAudioTactic = isAudioTactic;
const isVideoTactic = ({ type }) => type === 'video';
exports.isVideoTactic = isVideoTactic;
const isBreatheTactic = ({ type }) => type === 'breathe';
exports.isBreatheTactic = isBreatheTactic;
const isTaskTactic = ({ type }) => type === 'task';
exports.isTaskTactic = isTaskTactic;
const isContactsTactic = ({ type }) => type === 'contacts';
exports.isContactsTactic = isContactsTactic;
const isRecapTactic = ({ type }) => (0, lodash_1.keys)(recap_1.recapTacticSchemas).includes(type);
exports.isRecapTactic = isRecapTactic;
