"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.optionalStringArray = exports.requiredStringArray = exports.optionalArrayOf = exports.requiredArrayOf = void 0;
const yup_1 = require("yup");
const requiredArrayOf = (schema) => (0, yup_1.array)().of(schema).required();
exports.requiredArrayOf = requiredArrayOf;
const optionalArrayOf = (schema) => (0, yup_1.array)().of(schema).optional();
exports.optionalArrayOf = optionalArrayOf;
exports.requiredStringArray = (0, exports.requiredArrayOf)((0, yup_1.string)().required());
exports.optionalStringArray = (0, yup_1.array)().of((0, yup_1.string)().required());
