import * as yup from 'yup';

// Tactics can be generated by OpenAI
export const gptResponseMixin = {
  openAiRequestPayload: yup.string(),
  openAiChoiceResponse: yup.mixed().default(undefined),
};

export const gptMessageSchema = yup.object({
  role: yup
    .mixed<'system' | 'user' | 'assistant'>()
    .oneOf(['assistant', 'system', 'user'])
    .required(),
  content: yup.string().required(),
});
