import * as yup from 'yup';
import { questionSchema } from '../question';
import { objectOf } from '../utils/objectOf';
import { timestampSchema } from '../utils/timestamp';
import { logBaseSchema } from './base';
import { generatedMixin } from './utils/generated';

export const questionDataSchema = yup.object({
  numericValue: yup.number(),
  stringValue: yup.string().required(),
  unit: yup.string().required(),
  setAt: timestampSchema,
});
export type QuestionDataValue = yup.InferType<typeof questionDataSchema>;

export const questionsLogSchema = logBaseSchema('questions').shape({
  questionsById: objectOf(questionSchema),
  questionData: objectOf(questionDataSchema),
  ...generatedMixin, // These logs can be generated by OpenAI
});

export type QuestionsLogValue = yup.InferType<typeof questionsLogSchema>;
