import * as yup from 'yup';
import { strategySchema } from '../strategy';
import { requiredStringArray } from '../utils/array';
import { objectOf } from '../utils/objectOf';
import { logBaseSchema } from './base';
import { gptResponseMixin } from './utils/gpt';

export const strategiesLogSchema = logBaseSchema('strategies').shape({
  strategyIds: requiredStringArray,
  strategiesById: objectOf(strategySchema),
  // These are the tactics that the user has completed
  completedTacticIds: requiredStringArray,
  // ... and these are the tactics that Zara has followed up on with the user
  followedUpTacticIds: requiredStringArray,
  ...gptResponseMixin, // These logs can be generated by OpenAI
});

export type StrategiesLogValue = yup.InferType<typeof strategiesLogSchema>;
