import * as yup from 'yup';
import { tacticSchema } from '../strategy/tactic';
import { logBaseSchema } from './base';
import { generatedMixin } from './utils/generated';

export const tacticLogSchema = logBaseSchema('tactic').shape({
  tactic: tacticSchema.optional(),
  ...generatedMixin, // These logs can be generated by OpenAI
});

export type TacticLogValue = yup.InferType<typeof tacticLogSchema>;
