export const sampleImages = [
  'tactics/endless-constellation.png',
  'tactics/flat-mountains.png',
  'tactics/hollowed-boxes.png',
  'tactics/liquid-cheese.png',
  'tactics/quantum-gradient.png',
  'tactics/radiant-gradient.png',
  'tactics/rainbow-vortex.png',
  'tactics/rose-petals.png',
  'tactics/scattered-forcefields.png',
  'tactics/slanted-gradient.png',
  'tactics/subtle-prism.png',
  'tactics/sun-tornado.png',
  'tactics/wintery-sunburst.png',
];
